In [ ]:
import numpy as numpy
import pandas as pd

***Exportación del data set y primer análisis de los datos que contiene.***

In [3]:
df = pd.read_csv("/Users/alvarosanchez/ONLINE_DS_THEBRIDGE_ALVAROSMMS-1/EDA_Entrega/Data/Call Center.csv")
df

,id,customer_name,sentiment,csat_score,call_timestamp,reason,city,state,channel,response_time,call duration in minutes,call_center
0,DKK-57076809-w-055481-fU,Analise Gairdner,Neutral,7.0,10/29/2020,Billing Question,Detroit,Michigan,Call-Center,Within SLA,17,Los Angeles/CA
1,QGK-72219678-w-102139-KY,Crichton Kidsley,Very Positive,NaN,10/05/2020,Service Outage,Spartanburg,South Carolina,Chatbot,Within SLA,23,Baltimore/MD
2,GYJ-30025932-A-023015-LD,Averill Brundrett,Negative,NaN,10/04/2020,Billing Question,Gainesville,Florida,Call-Center,Above SLA,45,Los Angeles/CA
3,ZJI-96807559-i-620008-m7,Noreen Lafflina,Very Negative,1.0,10/17/2020,Billing Question,Portland,Oregon,Chatbot,Within SLA,12,Los Angeles/CA
4,DDU-69451719-O-176482-Fm,Toma Van der Beken,Very Positive,NaN,10/17/2020,Payments,Fort Wayne,Indiana,Call-Center,Within SLA,23,Los Angeles/CA
...,...,...,...,...,...,...,...,...,...,...,...,...
32936,BRM-96715111-h-155613-wO,Othelia Ouldcott,Neutral,NaN,10/30/2020,Billing Question,Oklahoma City,Oklahoma,Web,Within SLA,13,Denver/CO
32937,UJH-96531654-y-074703-H4,Tasha Cubbinelli,Negative,NaN,10/07/2020,Billing Question,Crawfordsville,Indiana,Chatbot,Within SLA,42,Baltimore/MD
32938,WDS-58440679-I-064360-TT,Margaux Slaten,Negative,NaN,10/04/2020,Billing Question,Lehigh Acres,Florida,Chatbot,Within SLA,30,Baltimore/MD
32939,FTZ-87704815-T-824288-iC,Odey Seed,Positive,8.0,10/27/2020,Payments,Salt Lake City,Utah,Call-Center,Within SLA,38,Baltimore/MD
32940,OOR-17971494-i-311571-PR,Mozelle Berlin,Negative,NaN,10/30/2020,Billing Question,Phoenix,Arizona,Call-Center,Within SLA,23,Baltimore/MD

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32941 entries, 0 to 32940
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        32941 non-null  object
 1   customer_name             32941 non-null  object
 2   sentiment                 32941 non-null  object
 3   csat_score                12271 non-null  float64
 4   call_timestamp            32941 non-null  object
 5   reason                    32941 non-null  object
 6   city                      32941 non-null  object
 7   state                     32941 non-null  object
 8   channel                   32941 non-null  object
 9   response_time             32941 non-null  object
 10  call duration in minutes  32941 non-null  int64
 11  call_center               32941 non-null  object
dtypes: float64(1), int64(1), object(10)
memory usage: 3.0+ MB

***Se observa que solo hay nulos en la columna "csat_score" lo cual es lógico ya que no todos los clientes tienden a valorar el contacto.***
***Aún así, se mantendrá esta columna sin modificaciones para poder sacar algunas conclusiones, además disponemos de la columna "sentiment" que está totalmente relacionada con la satisfacción del cliente".***

**Exploración y cambios que se van a realizar**

-Conversión de la columna "call_timestamp" a formato datetime.
-Valores únicos en las columnas:

   -"reason"

   -"channel"

   -"city"
   
   -"state"

In [5]:
df["call_timestamp"] = pd.to_datetime(df["call_timestamp"], format="%m/%d/%Y")
df = df.sort_values(by="call_timestamp")

In [8]:
columnas = ["reason","channel", "city", "state"]

for columna in columnas:
    print(f"\nValores únicos en '{columna}':")
    print(df[columna].unique())
    print(f"\nCantidad de ocurrencias en '{columna}':")
    print(df[columna].value_counts())

Valores únicos en 'reason':
['Billing Question' 'Payments' 'Service Outage']

Cantidad de ocurrencias en 'reason':
reason
Billing Question    23462
Payments             4749
Service Outage       4730
Name: count, dtype: int64

Valores únicos en 'channel':
['Email' 'Chatbot' 'Call-Center' 'Web']

Cantidad de ocurrencias en 'channel':
channel
Call-Center    10639
Chatbot         8256
Email           7470
Web             6576
Name: count, dtype: int64

Valores únicos en 'city':
['Buffalo' 'Charlottesville' 'Houston' 'Mobile' 'Washington' 'Phoenix'
 'Tallahassee' 'Topeka' 'San Diego' 'San Francisco' 'New York City'
 'Huntington' 'Bakersfield' 'Jacksonville' 'Saint Louis' 'Kansas City'
 'Newport News' 'Anchorage' 'Columbus' 'Roanoke' 'South Bend' 'Savannah'
 'New Orleans' 'Lexington' 'Decatur' 'Baltimore' 'Memphis' 'Tucson'
 'Minneapolis' 'Chicago' 'Rochester' 'Fort Wayne' 'Fairfax' 'Stamford'
 'Anaheim' 'Arlington' 'Asheville' 'Gainesville' 'Des Moines' 'Fresno'
 'Shawnee Mission' 'San Antonio' 'Saint Paul' 'Austin' 'Richmond' 'Boston'
 'Denver' 'Abilene' 'Dulles' 'Alpharetta' 'Boca Raton' 'Little Rock'
 'Hampton' 'North Hollywood' 'Oklahoma City' 'Albuquerque' 'Laurel'
 'Baton Rouge' 'Temple' 'Akron' 'Lancaster' 'Charlotte' 'Erie'
 'Huntsville' 'Boulder' 'Spokane' 'Louisville' 'Lincoln' 'Birmingham'
 'Dallas' 'Atlanta' 'Santa Barbara' 'Tacoma' 'Dayton' 'Detroit' 'Miami'
 'Peoria' 'Pittsburgh' 'Bridgeport' 'Orlando' 'Boise' 'Fort Lauderdale'
 'Indianapolis' 'Fort Worth' 'Iowa City' 'Colorado Springs' 'Syracuse'
 'Milwaukee' 'Hollywood' 'Los Angeles' 'Naperville' 'Duluth'
 'Battle Creek' 'Youngstown' 'Springfield' 'Bryan' 'Green Bay'
 'Scottsdale' 'Morgantown' 'Flint' 'Tulsa' 'Sacramento' 'Scranton'
 'Clearwater' 'Evansville' 'Santa Ana' 'Mountain View' 'Lawrenceville'
 'Las Vegas' 'Elmira' 'Pueblo' 'Nashville' 'El Paso' 'Young America'
 'Hialeah' 'Omaha' 'Saint Petersburg' 'Augusta' 'Brooksville' 'Cleveland'
 'Cincinnati' 'San Bernardino' 'Flushing' 'Ann Arbor' 'Newark'
 'North Little Rock' 'Seattle' 'Charleston' 'Glendale' 'Salt Lake City'
 'Corpus Christi' 'Fayetteville' 'Honolulu' 'Ocala' 'Provo'
 'Saint Augustine' 'Virginia Beach' 'Madison' 'Amarillo' 'Albany'
 'Daytona Beach' 'Naples' 'Visalia' 'Norman' 'Appleton' 'Wilkes Barre'
 'Escondido' 'Sandy' 'New Haven' 'Palatine' 'Racine' 'Oakland' 'Ashburn'
 'Mesa' 'Schenectady' 'Delray Beach' 'Irvine' 'Columbia' 'Southfield'
 'Santa Clara' 'Aurora' 'Modesto' 'White Plains' 'Waterbury' 'Greenville'
 'San Luis Obispo' 'Pensacola' 'Littleton' 'Stockton' 'Midland' 'Jamaica'
 'Inglewood' 'Grand Junction' 'Shreveport' 'Gilbert' 'Valdosta' 'Tampa'
 'Knoxville' 'Fort Pierce' 'Sioux Falls' 'San Jose' 'Falls Church'
 'Palmdale' 'Hartford' 'Fargo' 'Bradenton' 'Sunnyvale' 'Portland'
 'Henderson' 'Idaho Falls' 'Montgomery' 'Biloxi' 'Chattanooga'
 'Cedar Rapids' 'Raleigh' 'Wichita' 'Norfolk' 'Meridian' 'Alhambra'
 'Pasadena' 'Grand Rapids' 'Concord' 'Brooklyn' 'Galveston' 'Monticello'
 'Florence' 'Riverside' 'San Mateo' 'Muskegon' 'Orange' 'Lake Charles'
 'Seminole' 'Bronx' 'Anderson' 'Joliet' 'Bowie' 'Saginaw' 'Jefferson City'
 'Greeley' 'Hattiesburg' 'Lubbock' 'Spartanburg' 'Lynchburg' 'Sioux City'
 'Waltham' 'Pompano Beach' 'Great Neck' 'Killeen' 'Worcester' 'Bozeman'
 'Metairie' 'Valley Forge' 'Champaign' 'West Palm Beach' 'Tyler' 'London'
 'Sarasota' 'Huntington Beach' 'Lakeland' 'Humble' 'Boynton Beach'
 'Tuscaloosa' 'Chandler' 'Winston Salem' 'Lake Worth' 'Bismarck' 'Toledo'
 'Van Nuys' 'Fullerton' 'Zephyrhills' 'North Port' 'Durham'
 'Port Saint Lucie' 'Fairbanks' 'Fort Myers' 'Greensboro' 'Melbourne'
 'Waco' 'Trenton' 'Brockton' 'Terre Haute' 'Englewood' 'Marietta' 'Reno'
 'Spring Hill' 'Macon' 'Carol Stream' 'Santa Fe' 'Santa Monica'
 'Elizabeth' 'Crawfordsville' 'Carlsbad' 'Schaumburg' 'Rockford'
 'Carson City' 'Kalamazoo' 'Newton' 'Palo Alto' 'Vero Beach' 'Chesapeake'
 'Manchester' 'Ridgely' 'Bonita Springs' 'Harrisburg' 'Bloomington'
 'Alexandria' 'Philadelphia' 'Laredo' 'Conroe' 'Beaumont' 'Paterson'
 'Danbury' 'Canton' 'Whittier' 'New Castle' 'Mount Vernon' 'Las Cruces'
 'Bethesda' 'Lynn' 'Long Beach' 'Silver Spring' 'Reading' 'Lafayette'
 'Plano' 'Jackson' 'Anniston' 'Punta Gorda' 'Suffolk' 'Gadsden' 'Gastonia'
 'Annapolis' 'Warren' 'New Bedford' 'Monroe' 'Newport Beach'
 'West Hartford' 'Salem' 'Maple Plain' 'Lansing' 'Davenport' 'Montpelier'
 'Portsmouth' 'Panama City' 'Mc Keesport' 'Denton' 'Spring' 'Olympia'
 'Simi Valley' 'Kissimmee' 'Troy' 'Vancouver' 'Staten Island' 'Wilmington'
 'San Rafael' 'Saint Cloud' 'Petaluma' 'Providence' 'Cumming' 'Rockville'
 'Kent' 'Odessa' 'Loretto' 'Hamilton' 'Billings' 'Mesquite' 'Santa Rosa'
 'Santa Cruz' 'Redwood City' 'Port Washington' 'Eugene' 'Cheyenne'
 'Jersey City' 'Longview' 'Lehigh Acres' 'Irving' 'Garden Grove'
 'Saint Joseph' 'Chico' 'Palm Bay' 'Burbank' 'Round Rock' 'Corona'
 'Hot Springs National Park' 'Brea' 'Mansfield' 'Cape Coral' 'Everett'
 'Camden' 'York' 'Winter Haven' 'Lima' 'Moreno Valley' 'Merrifield'
 'Sterling' 'Bellevue' 'Jeffersonville' 'College Station' 'Gary'
 'Torrance' 'Levittown' 'Ventura' 'Fort Collins' 'Lakewood' 'Waterloo'
 'Athens' 'Missoula' 'Manassas' 'Oceanside' 'Hicksville' 'Hagerstown'
 'Fort Smith' 'Chula Vista' 'Dearborn' 'Helena' 'Gulfport' 'Hyattsville'
 'Bethlehem' 'Independence' 'Beaverton' 'Pocatello' 'Wichita Falls'
 'Muncie' 'Ogden' 'South Lake Tahoe' 'Evanston' 'Watertown' 'Aiken'
 'Vienna' 'Prescott' 'Berkeley' 'Edmond' 'North Las Vegas' 'Beaufort'
 'Allentown' 'Miami Beach' 'Johnstown' 'Oxnard' 'Kingsport' 'Arvada'
 'Johnson City' 'Yakima' 'Apache Junction' 'Garland' 'Fairfield' 'Sparks'
 'Texarkana' 'Homestead' 'High Point' 'Migrate' 'Port Charlotte'
 'New Hyde Park' 'New Brunswick' 'Largo' 'Salinas' 'Frederick'
 'Farmington' 'Cambridge' 'Gatesville' 'Murfreesboro' 'Grand Forks'
 'Juneau' 'Katy' 'Lees Summit' 'Pomona' 'Woburn' 'Tempe' 'Gaithersburg'
 'Norcross' 'Fredericksburg' 'East Saint Louis' 'Hayward' 'Herndon'
 'Frankfort' 'Pinellas Park' 'Yonkers' 'Norwalk' 'Reston' 'Utica'
 'San Angelo' 'Myrtle Beach' 'Northridge']

Cantidad de ocurrencias en 'city':
city
Washington       1110
Houston           657
New York City     564
El Paso           528
Dallas            437
                 ...
Myrtle Beach       10
Kingsport           9
Ridgely             9
Yonkers             7
Eugene              7
Name: count, Length: 461, dtype: int64

Valores únicos en 'state':
['New York' 'Virginia' 'Texas' 'Alabama' 'District of Columbia' 'Arizona'
 'Florida' 'Kansas' 'California' 'West Virginia' 'Missouri' 'Alaska'
 'Ohio' 'Indiana' 'Georgia' 'Louisiana' 'Kentucky' 'Maryland' 'Tennessee'
 'Minnesota' 'Illinois' 'Connecticut' 'North Carolina' 'Iowa'
 'Massachusetts' 'Colorado' 'Arkansas' 'Oklahoma' 'New Mexico'
 'Pennsylvania' 'Washington' 'Nebraska' 'Michigan' 'Idaho' 'Wisconsin'
 'Nevada' 'New Jersey' 'Utah' 'Hawaii' 'South Carolina' 'South Dakota'
 'North Dakota' 'Oregon' 'Mississippi' 'Montana' 'Delaware'
 'New Hampshire' 'Vermont' 'Rhode Island' 'Wyoming' 'Maine']

Cantidad de ocurrencias en 'state':
state
California              3631
Texas                   3572
Florida                 2834
New York                1786
Virginia                1164
Ohio                    1160
District of Columbia    1110
Pennsylvania            1017
Georgia                  926
Illinois                 848
North Carolina           765
Colorado                 742
Alabama                  738
Arizona                  737
Indiana                  736
Minnesota                712
Missouri                 682
Tennessee                664
Washington               663
Louisiana                627
Michigan                 612
Oklahoma                 538
Massachusetts            493
Kansas                   467
Nevada                   459
Maryland                 415
Kentucky                 411
Connecticut              408
Iowa                     366
Wisconsin                342
New Jersey               317
South Carolina           315
West Virginia            301
Utah                     298
Oregon                   261
Nebraska                 243
New Mexico               212
Arkansas                 204
Mississippi              178
Idaho                    174
Hawaii                   149
Alaska                   146
Delaware                 128
Montana                   94
South Dakota              93
North Dakota              76
New Hampshire             51
Rhode Island              35
Maine                     16
Vermont                   14
Wyoming                   11
Name: count, dtype: int64

***Revisión de las frecuencias ya que se ven ciertos valores por encima de otros.***

In [9]:
# Calcular frecuencias para cada columna
for columna in columnas:
    print(f"\nFrecuencias para la columna '{columna}':")
    
    # Frecuencia absoluta
    frecuencia_absoluta = df[columna].value_counts()
    print("Frecuencia Absoluta:")
    print(frecuencia_absoluta)
    
    # Frecuencia relativa
    frecuencia_relativa = df[columna].value_counts(normalize=True) * 100
    print("\nFrecuencia Relativa (%):")
    print(frecuencia_relativa)

Frecuencias para la columna 'reason':
Frecuencia Absoluta:
reason
Billing Question    23462
Payments             4749
Service Outage       4730
Name: count, dtype: int64

Frecuencia Relativa (%):
reason
Billing Question    71.224310
Payments            14.416684
Service Outage      14.359005
Name: proportion, dtype: float64

Frecuencias para la columna 'channel':
Frecuencia Absoluta:
channel
Call-Center    10639
Chatbot         8256
Email           7470
Web             6576
Name: count, dtype: int64

Frecuencia Relativa (%):
channel
Call-Center    32.297137
Chatbot        25.062991
Email          22.676907
Web            19.962964
Name: proportion, dtype: float64

Frecuencias para la columna 'city':
Frecuencia Absoluta:
city
Washington       1110
Houston           657
New York City     564
El Paso           528
Dallas            437
                 ...
Myrtle Beach       10
Kingsport           9
Ridgely             9
Yonkers             7
Eugene              7
Name: count, Length: 461, dtype: int64

Frecuencia Relativa (%):
city
Washington       3.369661
Houston          1.994475
New York City    1.712152
El Paso          1.602866
Dallas           1.326614
                   ...
Myrtle Beach     0.030357
Kingsport        0.027322
Ridgely          0.027322
Yonkers          0.021250
Eugene           0.021250
Name: proportion, Length: 461, dtype: float64

Frecuencias para la columna 'state':
Frecuencia Absoluta:
state
California              3631
Texas                   3572
Florida                 2834
New York                1786
Virginia                1164
Ohio                    1160
District of Columbia    1110
Pennsylvania            1017
Georgia                  926
Illinois                 848
North Carolina           765
Colorado                 742
Alabama                  738
Arizona                  737
Indiana                  736
Minnesota                712
Missouri                 682
Tennessee                664
Washington               663
Louisiana                627
Michigan                 612
Oklahoma                 538
Massachusetts            493
Kansas                   467
Nevada                   459
Maryland                 415
Kentucky                 411
Connecticut              408
Iowa                     366
Wisconsin                342
New Jersey               317
South Carolina           315
West Virginia            301
Utah                     298
Oregon                   261
Nebraska                 243
New Mexico               212
Arkansas                 204
Mississippi              178
Idaho                    174
Hawaii                   149
Alaska                   146
Delaware                 128
Montana                   94
South Dakota              93
North Dakota              76
New Hampshire             51
Rhode Island              35
Maine                     16
Vermont                   14
Wyoming                   11
Name: count, dtype: int64

Frecuencia Relativa (%):
state
California              11.022738
Texas                   10.843630
Florida                  8.603260
New York                 5.421815
Virginia                 3.533590
Ohio                     3.521447
District of Columbia     3.369661
Pennsylvania             3.087338
Georgia                  2.811086
Illinois                 2.574300
North Carolina           2.322334
Colorado                 2.252512
Alabama                  2.240369
Arizona                  2.237333
Indiana                  2.234298
Minnesota                2.161440
Missouri                 2.070368
Tennessee                2.015725
Washington               2.012689
Louisiana                1.903403
Michigan                 1.857867
Oklahoma                 1.633223
Massachusetts            1.496615
Kansas                   1.417686
Nevada                   1.393400
Maryland                 1.259828
Kentucky                 1.247685
Connecticut              1.238578
Iowa                     1.111077
Wisconsin                1.038220
New Jersey               0.962327
South Carolina           0.956255
West Virginia            0.913755
Utah                     0.904648
Oregon                   0.792326
Nebraska                 0.737683
New Mexico               0.643575
Arkansas                 0.619289
Mississippi              0.540360
Idaho                    0.528217
Hawaii                   0.452324
Alaska                   0.443217
Delaware                 0.388574
Montana                  0.285359
South Dakota             0.282323
North Dakota             0.230716
New Hampshire            0.154822
Rhode Island             0.106251
Maine                    0.048572
Vermont                  0.042500
Wyoming                  0.033393
Name: proportion, dtype: float64